// =============================================================================
//  build.mjs — ساختِ باندلِ self-contained از سایتِ web_tool برای اجرا روی Node
// =============================================================================
//  این اسکریپت را فقط «یک‌بار در سندباکس/کامپیوتر» اجرا می‌کنیم (نه روی گوشی).
//  خروجی: local-mobile/app.bundle.mjs — یک فایلِ تنها که کلِ منطقِ سایت (همهٔ
//  روترها و لایه‌های رکورد) + خودِ Hono را در خود دارد. این فایل در گیت commit
//  می‌شود تا کاربر روی گوشی فقط `git pull` بزند و مستقیم `node server.mjs` را
//  اجرا کند — بدونِ نیاز به esbuild/Vite/Wrangler و بدونِ npm install سنگین.
//
//  کلیدِ کار: importِ 'hono/cloudflare-workers' با alias به cf-shim.mjs نگاشت
//  می‌شود تا serveStatic روی Node کار کند. بقیهٔ کدِ سایت (که فقط Web-Fetch API
//  دارد) بدونِ تغییر باندل می‌شود.
//
//  اجرا:
//      cd local-mobile && node build.mjs
// =============================================================================

import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')                 // ریشهٔ ریپو

// esbuild داخلِ web_tool/node_modules نصب است (نه در local-mobile). آن را با
// مسیرِ مطلق import می‌کنیم تا این اسکریپت از هر cwd اجرا شود.
const esbuildPath = join(ROOT, 'web_tool', 'node_modules', 'esbuild', 'lib', 'main.js')
const { build } = await import(pathToFileURL(esbuildPath).href)
const ENTRY = join(ROOT, 'web_tool', 'src', 'index.tsx')
const SHIM = join(__dirname, 'cf-shim.mjs')
const OUT = join(__dirname, 'app.bundle.mjs')

console.log('▶ باندل‌سازیِ اپِ کاملِ سایت (همهٔ لایه‌های رکورد) ...')
console.log('  ورودی :', ENTRY)
console.log('  alias  : hono/cloudflare-workers →', SHIM)
console.log('  خروجی :', OUT)

await build({
  entryPoints: [ENTRY],
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node18',
  outfile: OUT,
  // منطقِ سایت را دست‌نخورده نگه می‌داریم؛ فقط ماژولِ استاتیکِ کلادفلر را
  // به shimِ سازگارِ Node نگاشت می‌کنیم. hono و hono/serve-static داخلِ باندل
  // قرار می‌گیرند (self-contained) — پس گوشی به node_modules نیاز ندارد.
  alias: {
    'hono/cloudflare-workers': SHIM,
  },
  // cf-shim.mjs در پوشهٔ local-mobile است که node_modules ندارد؛ به esbuild
  // می‌گوییم ماژول‌ها (مثلِ hono/serve-static) را از web_tool/node_modules پیدا کند.
  nodePaths: [join(ROOT, 'web_tool', 'node_modules')],
  // چیزی external نمی‌گذاریم تا باندل کاملاً مستقل شود.
  banner: {
    js: '// AUTO-GENERATED by local-mobile/build.mjs — کلِ منطقِ سایت + Hono در این فایل است. دستی ویرایش نکنید.',
  },
  logLevel: 'info',
})

// ---------------------------------------------------------------------------
// 🔏 اثرِ انگشتِ منبع — قرینهٔ نگهبانِ کهنگی در server.mjs.
// ---------------------------------------------------------------------------
// باندل باید بداند «از کدام نسخهٔ کد ساخته شده‌ام». نسخهٔ اولِ این سازوکار برای
// همین کار `mtime` را مقایسه می‌کرد و هشدارِ کاذب می‌داد: `git pull` زمانِ فایل
// را روی لحظهٔ دانلود می‌گذارد و ترتیبِ نوشتن هم تضمینی نیست، پس بعد از هر pullِ
// سالم چند فایل تصادفاً جلوتر از باندل مهر می‌خوردند.
//
// این‌جا به‌جای زمان، **محتوا** ثبت می‌شود: هشِ مسیر+بایتِ همهٔ فایل‌های ts/tsx.
// الگوریتم عمداً مو‌به‌مو همان چیزی است که `server.mjs` اجرا می‌کند (ترتیبِ
// الفبایی، مسیرِ نسبی، سپس محتوا)؛ اگر این دو از هم فاصله بگیرند، نگهبان دوباره
// دروغ می‌گوید — پس هر تغییری در یکی باید در دیگری هم بیفتد.
{
  const { readdirSync, readFileSync, writeFileSync } = await import('node:fs')
  const { createHash } = await import('node:crypto')
  const srcDir = join(ROOT, 'web_tool', 'src')
  const files = []
  const walk = (dir) => {
    for (const ent of readdirSync(dir, { withFileTypes: true }).sort((x, y) => x.name < y.name ? -1 : 1)) {
      const p = join(dir, ent.name)
      if (ent.isDirectory()) walk(p)
      else if (/\.(ts|tsx)$/.test(ent.name)) files.push(p)
    }
  }
  walk(srcDir)
  const h = createHash('sha1')
  for (const f of files) { h.update(f.slice(srcDir.length)); h.update(readFileSync(f)) }
  writeFileSync(join(__dirname, '.bundle-src-hash'), h.digest('hex') + '\n')
  console.log(`🔏 اثرِ انگشتِ منبع ثبت شد (${files.length} فایل).`)
}

console.log('✅ ساختِ app.bundle.mjs کامل شد.')
