// =============================================================================
//  build.mjs — ساختِ باندلِ self-contained از سایتِ web_tool برای اجرا روی Node
// =============================================================================
//  این اسکریپت را فقط «یک‌بار در سندباکس/کامپیوتر» اجرا می‌کنیم (نه روی گوشی).
//  خروجی: local-mobile/app.bundle.mjs — یک فایلِ تنها که کلِ منطقِ سایت (همهٔ
//  روترها و لایه‌های رکورد) + خودِ Hono را در خود دارد. این فایل در گیت commit
//  می‌شود تا کاربر روی گوشی فقط `git pull` بزند و مستقیم `node server.mjs` را
//  اجرا کند — بدونِ نیاز به esbuild/Vite/Wrangler و بدونِ npm install سنگین.
//
//  کلیدِ کار: importِ 'hono/cloudflare-workers' با alias به cf-shim.mjs نگاشت
//  می‌شود تا serveStatic روی Node کار کند. بقیهٔ کدِ سایت (که فقط Web-Fetch API
//  دارد) بدونِ تغییر باندل می‌شود.
//
//  اجرا:
//      cd local-mobile && node build.mjs
// =============================================================================

import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')                 // ریشهٔ ریپو

// esbuild داخلِ web_tool/node_modules نصب است (نه در local-mobile). آن را با
// مسیرِ مطلق import می‌کنیم تا این اسکریپت از هر cwd اجرا شود.
const esbuildPath = join(ROOT, 'web_tool', 'node_modules', 'esbuild', 'lib', 'main.js')
const { build } = await import(pathToFileURL(esbuildPath).href)
const ENTRY = join(ROOT, 'web_tool', 'src', 'index.tsx')
const SHIM = join(__dirname, 'cf-shim.mjs')
const OUT = join(__dirname, 'app.bundle.mjs')

console.log('▶ باندل‌سازیِ اپِ کاملِ سایت (همهٔ لایه‌های رکورد) ...')
console.log('  ورودی :', ENTRY)
console.log('  alias  : hono/cloudflare-workers →', SHIM)
console.log('  خروجی :', OUT)

await build({
  entryPoints: [ENTRY],
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node18',
  outfile: OUT,
  // منطقِ سایت را دست‌نخورده نگه می‌داریم؛ فقط ماژولِ استاتیکِ کلادفلر را
  // به shimِ سازگارِ Node نگاشت می‌کنیم. hono و hono/serve-static داخلِ باندل
  // قرار می‌گیرند (self-contained) — پس گوشی به node_modules نیاز ندارد.
  alias: {
    'hono/cloudflare-workers': SHIM,
  },
  // cf-shim.mjs در پوشهٔ local-mobile است که node_modules ندارد؛ به esbuild
  // می‌گوییم ماژول‌ها (مثلِ hono/serve-static) را از web_tool/node_modules پیدا کند.
  nodePaths: [join(ROOT, 'web_tool', 'node_modules')],
  // چیزی external نمی‌گذاریم تا باندل کاملاً مستقل شود.
  banner: {
    js: '// AUTO-GENERATED by local-mobile/build.mjs — کلِ منطقِ سایت + Hono در این فایل است. دستی ویرایش نکنید.',
  },
  logLevel: 'info',
})

console.log('✅ ساختِ app.bundle.mjs کامل شد.')
